# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test-app:
    docker:
      # specify the version you desire here
      - image: circleci/node:lts-jessie-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-app-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-app-dependencies-

      - run: cd src/tests && yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-app-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: cd src/tests && yarn test

  test-ui:
    docker:
      # specify the version you desire here
      - image: circleci/node:lts-jessie-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-ui-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-ui-dependencies-

      - run: cd src/popup && yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-ui-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: cd src/tests && yarn test

workflows:
  version: 2
  test_app_ui:
    jobs:
      - test-app
      - test-ui